# Generated by Django 4.1.3 on 2022-12-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
